---
deployment:
  tasks:
    - export DEPLOYPATH=/home/midappbi/repositories/midapp/
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH