---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kriswangsaputra04@gmail.com/public_html/midapp/
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH